### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by panosz** [hiddenSymmetries/booz_xform#1]
Hi there. I believe there is a small typo in equation 11 in the section "Theory and numerical Implementation". 

The equation reads:  
> G = \hat{B}_{\zeta_0, 0, 0}^s,

However, I believe it should be: 
> G = \hat{B}_{\zeta_0, 0, 0}^c.

If I am not mistaken, this is the formula used in [the source code](https://github.com/hiddenSymmetries/booz_xform/blob/d6882133762312aefa7c3cfd50ec081adf2c8998/src/_booz_xform/surface_solve.cpp#L101)

**Comment by landreman** [comment]
Well spotted. Fixed now. Thanks.
