### ISSUE TITLE
Running on an asymmetric equilibrium does not save the asymmetric quantities

### ISSUE THREAD

**Issue by dpanici** [hiddenSymmetries/booz_xform#15]
I am running this version of booz_xform to benchmark the DESC implementation of the boozmn.nc style output files, and for asymmetric cases I noticed that the saved `.nc` file from this `booz_xform` does not seem to save the asymmetric quantities, even though they are calculated and accessible through the structure after `b.run()` is called. printing `b.asym` results in `True` so the flag seems to be set correctly, and the quantities do end up being calculated so it is probably just a logic thing in the write call.

Maybe I am doing something wrong with the write call, but I don't thing the write call takes any arguments. My script is shown here, I end up saving the asymmetric quantiites as `.npy` files to get around this 

```python
import booz_xform as bx
import time

t = time.time()
b = bx.Booz_xform()
nsurfs=100
b.read_wout(f"wout_QA_asym_{nsurfs}_surfs.nc")
b.mboz =40
b.nboz = 40
print(b.asym)
#print(b.compute_surfs)
b.run()
print(b.rmns_b)

import numpy as np
np.save(f"rmns_b_{nsurfs}_{b.mboz}.npy",b.rmns_b)

np.save(f"zmnc_b_{nsurfs}_{b.mboz}.npy",b.zmnc_b)
np.save(f"bmns_b_{nsurfs}_{b.mboz}.npy",b.bmns_b)
np.save(f"gmns_b_{nsurfs}_{b.mboz}.npy",b.gmns_b)
np.save(f"pmnc_b_{nsurfs}_{b.mboz}.npy",-b.pmnc_b) # negated to abide by the legacy sign convention

b.write_boozmn(f"boozmn_{nsurfs}_surfs_QA_asym_sims_booz_{b.mboz}.nc")
print(f"time taken: {time.time()-t} s")```

**Comment by landreman** [comment]
Hi @dpanici , I tried your example just now with the non-stellarator-symmetric equilibria `tests/test_files/wout_up_down_asymmetric_tokamak.nc` and `tests/test_files/wout_LandremanSenguptaPlunk_section5p3.nc`. In both cases, I do see the fields `rmns_b`, `zmnc_b`, `bmns_b`, `gmns_b`, and `pmnc_b` in the `.nc` output file. The logic for writing these fields is [here](https://github.com/hiddenSymmetries/booz_xform/blob/main/src/_booz_xform/write_boozmn.cpp#L119-L137), and looks ok. Do you experience the problem with those two specific wout files in the repo?

**Comment by dpanici** [comment]
Ah sorry, I realize I was using an older pip version `0.0.6`, this is working now with `0.0.8`. Thanks!
